### ISSUE TITLE
Multi world editing

### ISSUE THREAD

**Issue by TaisenSchettler** [MinervaTools/MinervaTools#6]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a checkbox for every world to the world list. if you tick multiple worlds you can download or delete multiple worlds at once.

**Describe alternatives you've considered**
no

**Additional context**
Helping the user keep the server clean is key!

**Comment by Unkn0wnCat** [comment]
I've added this and it will be in v1.4.0.
