### ISSUE TITLE
World renaming

### ISSUE THREAD

**Issue by TaisenSchettler** [MinervaTools/MinervaTools#7]
**Is your feature request related to a problem? Please describe.**
Worlds could be uploaded with the wrong name. to change the world name we have to rename it.

**Describe the solution you'd like**
An in-game command like `/minerva rename "current name" "new name"`
And an option to change the world name over the web interface

**Describe alternatives you've considered**
Only command or web interface usage.

**Additional context**
users are incompetent.

**Comment by Unkn0wnCat** [comment]
Done, will be in 1.4.0
