### ISSUE TITLE
/wtp TAB liste sorting

### ISSUE THREAD

**Issue by TaisenSchettler** [MinervaTools/MinervaTools#9]
**Describe the bug**
The autocomplete list for the /wtp command is not sorted correctly.

**To Reproduce**
type /wtp %worldname% try to auto complete

**Expected behavior**
The started worldname should be autocomplete based on that.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/39908691/134810829-02711593-54c0-49d8-957e-13b34d1c0704.png)

**Server (please complete the following information):**
-naa

**Additional context**
pls fix

**Comment by Unkn0wnCat** [comment]
Should work better now
